
import React from 'react';
import { ModalBase } from './ModalBase';

export const TermsModal: React.FC<{ isOpen: boolean; onClose: () => void; }> = ({ isOpen, onClose }) => {
  return (
    <ModalBase isOpen={isOpen} onClose={onClose} title="Terms of Service">
      <div className="space-y-4 text-slate-300 text-sm">
        <p>By using this demo application ("Service"), you agree to these terms and conditions.</p>
        
        <h3 className="font-bold text-slate-100 pt-2 border-t border-slate-700">1. Nature of the Service</h3>
        <p>This Service is a technology demonstration provided "as-is" without any warranties. It is not intended for production or commercial use and may contain errors or inaccuracies.</p>
        
        <h3 className="font-bold text-slate-100 pt-2 border-t border-slate-700">2. User-Generated Content</h3>
        <p>
          The content generated by the AI is for informational and creative purposes only. You are solely responsible for reviewing, editing, and ensuring the accuracy and appropriateness of any content before you use it. We claim no ownership over the content you generate.
        </p>

        <h3 className="font-bold text-slate-100 pt-2 border-t border-slate-700">3. Acceptable Use</h3>
        <p>
          You agree not to use this Service to generate content that is illegal, harmful, offensive, or infringing on the rights of others. You also agree to abide by the terms of service of the underlying Google Gemini API.
        </p>

        <h3 className="font-bold text-slate-100 pt-2 border-t border-slate-700">4. Intellectual Property</h3>
        <p>
          The Service and its original content, features, and functionality are and will remain the exclusive property of PersonaGen AI and its licensors.
        </p>
        
        <h3 className="font-bold text-slate-100 pt-2 border-t border-slate-700">5. Limitation of Liability</h3>
        <p>
          In no event shall we be liable for any indirect, incidental, or consequential damages arising out of or in connection with your use of the Service.
        </p>
      </div>
    </ModalBase>
  );
};
